---
- name: Install Ansible Host Baseline
  hosts: all
  become: yes
  become_user: root
  remote_user: root
  vars_files:
    - "{{ playbook_dir }}/vars/base.yml"
  tasks:
    - name: Build image
      include_tasks:
        file: "{{ playbook_dir }}/jobs/build/build.yml"
