---
version: "2.4"
services:
  ptg-ansible:
    build:
      context: .
      # args:
    image: penguintech/ubuntu-ansible
    volumes:
      - ptg-vars:/opt/core/vars # This will be /opt/manager/vars for standard apps
    networks:
      - buildme
volumes:
  ptg-vars:
networks:
  buildme:
