---
version: "2.4"
services:
  ptg-ansible:
    build:
      context: .
      #args:
    image: penguintech/ubuntu-ansible
    volumes:
      - ptg-vars:/opt/manager/vars
    networks:
      - buildme
volumes:
  ptg-vars:
networks:
  buildme: