---
- name: Install Ansible Host Baseline
  hosts: all
  become: true
  vars_files:
    - "{{ playbook_dir }}/vars/base.yml"
  tasks:
    - name: Build image
      include_tasks: "{{ playbook_dir }}/jobs/run/update.yml"
