---
- name: Install Ansible Host Baseline
  hosts: all
  strategy: linear
  serial: 3
  become: yes
  remote_user: root
  roles:
    - kwoodson.yedit
  vars:
    PriamryIf: enp1s0
    nextFreeIf: enp6s0
  tasks:
    - name: Update and get container to standard point
      include_tasks: 
        file: jobs/initialize.yaml
        apply:
          tags:
            - enviro
      tags:
        - enviro
    - name: Setup local interface
      include_tasks:
        file: jobs/configure/local_interface.yaml
        apply:
          tags:
            - enviro
            - interface
            - first
      tags:
        - enviro
        - interface
        - first