---
- name: Install Ansible Host Baseline
  hosts: all
  become: yes
  become_user: root
  remote_user: root
  roles:
    - kwoodson.yedit
  vars_files:
    - vars/base.yml
  tasks:
    - name: Disable problematic unattended Upgrades
      include_tasks:
        file: jobs/build/disableunattended.yml
        apply:
          tags:
            - build
            - metal
      tags:
        - build
        - metal
    - name: Setup network interfaces
      include_tasks:
        file: jobs/run/networking.yml
        apply:
          tags:
            - interface
            - build
            - metal
      tags:
        - interface
        - build
        - metal
    - name: Setup DNS
      include_tasks:
        file: jobs/build/dns.yml
        apply:
          tags:
            - dns
            - build
            - metal
      tags:
        - dns
        - build
        - metal
    - name: Install container libraries
      include_tasks: 
        file: jobs/build/installlibraries.yml
        apply:
          tags:
            - build
      tags:
        - build
    - name: Update container libraries
      include_tasks: 
        file: jobs/run/update.yml
        apply:
          tags:
            - build
            - run
            - update
      tags:
        - build
        - run
        - update
    - name: Enable kernel Mods
      include_tasks:
        file: jobs/build/kernelmods.yml
        apply:
          tags:
            - build
            - metal
      tags:
        - build
        - metal
      when: kmod
    - name: Setup twice daily updates via crontab
      include_tasks:
        file: jobs/build/autoupdate.yml
        apply:
          tags:
            - build
      tags:
        - build
    - name: Setup SystemD
      include_tasks:
        file: jobs/build/systemd
        apply:
          tags:
            - build
            - metal
      tags:
        - build
        - metal
    - name: Install Docker
      include_tasks:
        file: jobs/build/docker.yml
        apply:
          tags:
            - metal
            - build
      tags:
        - docker
        - build
      when: docker
    - name: Install User
      include_tasks:
        file: jobs/build/user.yml
        apply:
          tags:
            - build
      tags:
        - build
      when: docker