---
- name: Install Ansible Host Baseline
  hosts: all
  become: yes
  become_user: root
  roles:
    - kwoodson.yedit
  vars:
    PrimaryIf: enp1s0
    nextFreeIf: enp6s0
  tasks:
    - name: Disable problematic unattended Upgrades
      include_tasks:
        file: jobs/install/unattended.yaml
        apply:
          tags:
            - enviro
        tags:
          - enviro
    - name: Update and get container to standard point
      include_tasks: 
        file: jobs/run/system.yaml
        apply:
          tags:
            - enviro
      tags:
        - enviro
    - name: Setup local interface
      include_tasks:
        file: jobs/configure/local_interface.yaml
        apply:
          tags:
            - enviro
            - interface
            - first
      tags:
        - enviro
        - interface
        - first