---
- name: Install Ansible Host Baseline
  hosts: all
  become: yes
  become_user: root
  remote_user: root
  roles:
    - kwoodson.yedit
  vars_file:
    - vars/system.yaml
  tasks:
    - name: Disable problematic unattended Upgrades
      include_tasks:
        file: jobs/install/unattended.yaml
        apply:
          tags:
            - enviro
      tags:
        - enviro
    - name: Update and get container to standard point
      include_tasks: 
        file: jobs/run/system.yaml
        apply:
          tags:
            - enviro
            - system
      tags:
        - enviro
    - name: Setup twice daily updates
      include_tasks:
        file: jobs/install/autoupdate.yaml
        apply:
          tags:
            - enviro
            - first
      tags:
        - enviro
        - first
    - name: Setup local interface
      include_tasks:
        file: jobs/configure/local_interface.yaml
        apply:
          tags:
            - enviro
            - interface
            - first
      tags:
        - enviro
        - interface
        - first