---
- name: Install Ansible Host Baseline
  hosts: all
  become: yes
  become_user: root
  remote_user: root
  vars_files:
    - vars/base.yml
  tasks:
    - name: Build image
      include_tasks:
        file: jobs/build/build.yml
        apply:
          tags:
            - build
      tags:
        - build

