---
dns-defaults:
  - 1.1.1.1
  - 8.8.8.8
dns: "{{ lookup('env', 'DNS') | default( dns-defaults, True) }}"
interfaces:
  public: "{{ lookup('env', 'PUBLIC_INTERFACE') | default('enp1s0', True) }}"
  private: "{{ lookup('env', 'INTERNAL_INTERFACE') | default('enp6s0', True) }}"
kmod:  "{{ lookup('env', 'KERNEL_MODS') | default('yes', True) }}"
docker: "{{ lookup('env', 'DOCKER') | default('yes', True) }}"
update: "{{ lookup('env', 'CRON_UPDATE') | default('yes', True) }}