---
- name: copy template to public interface
  copy:
    src: "{{ playbook_dir }}/configs/10-netplan.yaml"
    dest: "/etc/netplan/10-{{ PriamryIf }}.yaml"
    backup: yes
- name: update config for name
  ansible.builtin.lineinfile:
    path: "/etc/netplan/10-{{ PriamryIf }}.yaml"
    search_string: enp1s0
    line: "        {{ PriamryIf }}:"
    create: yes
- name: copy template to internal interface
  copy:
    src: "{{ playbook_dir }}/configs/20-netplan.yaml"
    dest: "/etc/netplan/20-{{ nextFreeIf }}.yaml"
- name: update config for name
  ansible.builtin.lineinfile:
    path: "/etc/netplan/20-{{ nextFreeIf }}.yaml"
    search_string: enp6s0
    line: "        {{ nextFreeIf }}:"
    create: yes
- name: update IP
  ansible.builtin.lineinfile:
    path: "/etc/netplan/20-{{ nextFreeIf }}.yaml"
    search_string: 10.0.0.1/24
    line: "                - {{ localip }}"
    create: no
- name: Initiate netplan
  shell: netplan apply