---
all:
  hosts:
    localhost:
      vars:
        PriamryIf: enp1s0
        nextFreeIf: enp6s0
        localip: 10.2.144.3/24
  children:
    cluster:
      hosts:
      var:
        environment: prod
    dev:
      hosts:
      var:
        environment: dev