---
- name: Install Docker GPG Key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /usr/share/keyrings/docker-archive-keyring.gpg
    state: present
- name: Get OS code name
  shell: lsb_release -cs
  register: release
- name: Install Docker PPA
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ release.stdout }} stable"
    state: present
    filename: docker
    update_cache: yes
- name: Install Docker-CE (which has less issues with kube and prod apps)
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
- name: Copy Daemon file
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/configs/daemon.json"
    dest: /etc/docker/daemon.json
- name: enable overlay
  community.general.modprobe:
    name: overlay
    state: present
- name: Enable Docker services
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
    daemon_reload: yes
  loop:
    - docker